#library "myscripts.acs"
#include "zcommon.acs"


global int 1:x;
global bool 2:raised;

script 100 ENTER{
	x=1;
	raised = FALSE;
}

/*
SCRIPT 1:
---------
*/
script 1 (int direction){

	if(direction){
		if(x<3){
			x++;
		}
	}
	else{
		if(x>0){
			x--;
		}
	}
	print(i:x);
	if(x==3 &! raised){
		print(s:"raising...");
		raised = TRUE;
		Ceiling_RaiseByValue(1,12,64);
	}
	if(x==0 && raised){
		print(s:"lowering...");
		raised = FALSE;
		Ceiling_LowerByValue(1,12,64);
	}
}

script 2 (void){
	
}

script 3 (void){
	log(i:x);
}
